routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', \App\Http\Livewire\Grid::class)->name('grid');
Route::get('/departments', \App\Http\Livewire\Departments::class)->name('departments');
Route::get('/employees', \App\Http\Livewire\Employees::class)->name('employees');

app/Models/Department.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    use HasFactory;

    protected $fillable = ['title'];

    public function employees(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(Employee::class);
    }

    public function delete()
    {
        if($this->employees->count() > 0 ){

            session()->flash('warning',__('В отделе есть сотрудники. Удаление запрещено.'));
            return false;
        };

        return parent::delete();
    }
}

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use HasFactory;

    protected $fillable = [
        'first_name',
        'middle_name',
        'last_name',
        'gender',
        'salary',
        ];

    public function departments(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(Department::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DepartmentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DepartmentController extends Controller
{
    //
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    //
}

app/Http/Livewire/Departments.php
<?php

namespace App\Http\Livewire;

use App\Models\Department;
use Livewire\Component;

class Departments extends Component
{
    //List of Departments for table
    public $departments;

    //Data for add/edit Department
    public $department = [];
    public $departmentId;

    //Is modal for add or update
    public $update = false;
    public $title;

    protected $rules = [
        'department.title' => 'required',
    ];

    public function render()
    {
        $this->departments = Department::withCount('employees')
            ->withMax('employees','salary')
            ->get();
        return view('livewire.departments.index');
    }

    public function add()
    {
        $this->update = false;
        $this->resetInputFields();

        $this->dispatchBrowserEvent('showDepartmentModal');
    }

    public function edit(Department $department)
    {
        $this->update = true;
        $this->department = $department->toArray();
        $this->departmentId = $department->id;

        $this->dispatchBrowserEvent('showDepartmentModal');
    }

    public function store()
    {
        $this->validate();

        Department::create($this->department);

        session()->flash('success',__('Успешно добавлено.'));
        $this->closeModal();
    }

    public function update(Department $department)
    {
        $this->validate();

        $department->update($this->department);

        session()->flash('success',__('Успешно сохранено.'));
        $this->closeModal();
    }

    public function delete(Department $department)
    {
        if($department->delete()){
            session()->flash('success',__('Успешно удалено.'));
        }
    }

    private function closeModal()
    {
        $this->resetInputFields();
        $this->dispatchBrowserEvent('closeDepartmentModal');
    }

    private function resetInputFields()
    {
        $this->reset(['department', 'departmentId']);
        $this->resetErrorBag();
    }
}

app/Http/Livewire/Employees.php
<?php

namespace App\Http\Livewire;

use App\Models\Department;
use App\Models\Employee;
use Livewire\Component;

class Employees extends Component
{
    //List of Departments for add/edit form
    public $departments;

    //List of Employees for table
    public $employees;

    //Data for add/edit Employee
    public $employee = [];
    public $employeeId;

    //Is modal for add or update
    public $update = false;

    protected $rules = [
        'employee.first_name' => 'required',
        'employee.last_name' => 'required',
        'employee.salary' => 'integer',
        'employee.departments' => 'required|array',
    ];

    public function render()
    {
        $this->employees = Employee::with('departments')->get();
        $this->departments = Department::all();
        return view('livewire.employees.index');
    }

    //Open add new ModalForm
    public function add()
    {
        $this->update = false;
        $this->resetInputFields();

        $this->dispatchBrowserEvent('showEmployeeModal');
    }

    //Open edit ModalForm
    public function edit(Employee $employee)
    {
        $this->update = true;
        $this->employeeId = $employee->id;
        $this->employee = $employee->toArray();
        $this->employee['departments'] = $employee->departments->pluck('id')->toArray();

        $this->dispatchBrowserEvent('showEmployeeModal');
    }

    public function store()
    {
        $this->validate();

        $employee = Employee::create($this->employee);
        $employee->departments()->sync($this->employee['departments']);

        session()->flash('success',__('Успешно добавлено.'));
        $this->closeModal();
    }

    public function update(Employee $employee)
    {
        $this->validate();

        $employee->update($this->employee);
        $employee->departments()->sync($this->employee['departments']);

        session()->flash('success',__('Успешно сохранено.'));
        $this->closeModal();
    }

    public function delete(Employee $employee)
    {
        if($employee->delete()){
            session()->flash('success',__('Успешно удалено.'));
        }
    }

    private function closeModal()
    {
        $this->resetInputFields();
        $this->dispatchBrowserEvent('closeEmployeeModal');
    }

    private function resetInputFields()
    {
        $this->reset(['employee', 'employeeId']);
        $this->resetErrorBag();
    }
}

app/Http/Livewire/Grid.php
<?php

namespace App\Http\Livewire;

use App\Models\Department;
use App\Models\Employee;
use Livewire\Component;

class Grid extends Component
{
    public $departments;
    public $employees;

    public function mount()
    {

        $this->departments = Department::with('employees')->get();
        $this->employees = Employee::all();
    }

    public function render()
    {
        return view('livewire.grid');
    }
}

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <title>{{ config('app.name', 'Laravel') }}</title>

    @livewireStyles
</head>
<body class="bg-light">

    <nav class="justify-content-center navbar navbar-expand-lg top navbar-dark bg-dark" aria-label="Main navigation">
        <div class="d-flex">
            <div class="navbar-collapse offcanvas-collapse" id="navbar">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link @if(Route::currentRouteName() == 'grid') active @endif" href="{{route('grid')}}">@lang("Сетка")</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link @if(Route::currentRouteName() == 'departments') active @endif" href="{{route('departments')}}">@lang("Отделы")</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link @if(Route::currentRouteName() == 'employees') active @endif" href="{{route('employees')}}">@lang("Сотрудники")</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <main class="container mt-3">
        {{ $slot }}
    </main>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.8.2/dist/alpine.min.js" defer></script>

    @livewireScripts

    @yield('scripts')

</body>
</html>

resources/views/livewire/departments/add-modal.blade.php
    <div wire:ignore.self id="departmentModal" class="modal fade" tabindex="-1" >
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">
                        @if($update)
                            @lang('Редактировать отдел')
                        @else
                            @lang('Новый отдел')
                        @endif
                    </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>

                @include('partials.input-alerts')

                <form wire:submit.prevent="{{($update) ? 'update('.$departmentId.')' : 'store()' }}">
                    <div class="modal-body">
                        <div class="mb-3">
                            <label for="departmentTitle" class="form-label">@lang('Название отдела')</label>
                            <input required wire:model.defer="department.title" type="text" class="form-control @error('department.title') is-invalid @enderror" id="departmentTitle">
                            <div class="invalid-feedback">
                                @error('department.title') <span class="error">{{ $message }}</span> @enderror
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">@lang('Отмена')</button>
                        <button type="submit" class="btn btn-primary" >@lang('Сохранить')</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

resources/views/livewire/departments/index.blade.php
<div>
    @include('partials.alerts')

    <div class="card">
        <div class="card-header">
            @lang("Отделы")
        </div>
        <div class="card-body">
            <button wire:click="add()" type="button" class="btn btn-primary mb-3">@lang('Добавить')</button>
            <table class="table table-hover table-bordered">
                <thead>
                <tr>
                    <th scope="col">@lang('Название отдела')</th>
                    <th scope="col">@lang('Количество сотрудников')</th>
                    <th scope="col">@lang('Максимальная заработная плата')</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody>
                    @foreach($departments as $department)
                        <tr>
                            <td>{{$department->title}}</td>
                            <td>{{$department->employees_count}}</td>
                            <td>{{$department->employees_max_salary}}</td>
                            <td>
                                <button wire:click="edit({{$department->id}})" type="button" class="btn btn-primary">@lang("Edit")</button>
                                <button wire:click="delete({{$department->id}})" type="button" class="btn btn-danger">@lang("Delete")</button>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

    @include('livewire.departments.add-modal')

    @section('scripts')
        <script>
            window.addEventListener('closeDepartmentModal',function (){
                $('#departmentModal').modal('hide');
            });
            window.addEventListener('showDepartmentModal',function (){
                $('#departmentModal').modal('show');
            });
        </script>
    @endsection
</div>

resources/views/livewire/employees/add-modal.blade.php
<div wire:ignore.self id="employeeModal" class="modal fade" tabindex="-1" >
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">
                    @if($update)
                        @lang('Редактировать сотрудника')
                    @else
                        @lang('Новый сотрудник')
                    @endif
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>

            @include('partials.input-alerts')

            <form wire:submit.prevent="{{($update) ? 'update('.$employeeId.')' : 'store()' }}">
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="employeeFirstName" class="form-label">@lang('Имя')</label>
                        <input required wire:model.defer="employee.first_name" type="text" class="form-control @error('employee.first_name') is-invalid @enderror" id="employeeFirstName">
                        <div class="invalid-feedback">
                            @error('employee.first_name') <span class="error">{{ $message }}</span> @enderror
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="employeeLastName" class="form-label">@lang('Фамилия')</label>
                        <input required wire:model.defer="employee.last_name" type="text" class="form-control @error('employee.last_name') is-invalid @enderror" id="employeeLastName">
                        <div class="invalid-feedback">
                            @error('employee.last_name') <span class="error">{{ $message }}</span> @enderror
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="employeeMiddleName" class="form-label">@lang('Отчество')</label>
                        <input wire:model.defer="employee.middle_name" type="text" class="form-control @error('employee.middle_name') is-invalid @enderror" id="employeeMiddleName">
                        <div class="invalid-feedback">
                            @error('employee.middle_name') <span class="error">{{ $message }}</span> @enderror
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="employeeGender" class="form-label">@lang('Пол')</label>
                        <select wire:model.defer="employee.gender" class="custom-select @error('employee.gender') is-invalid @enderror" id="employeeGender">
                            <option selected value="">@lang('Выберите пол')</option>
                            <option value="male">@lang('male')</option>
                            <option value="female">@lang('female')</option>
                        </select>
                        <div class="invalid-feedback">
                            @error('employee.gender') <span class="error">{{ $message }}</span> @enderror
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="employeeSalary" class="form-label">@lang('Заработная плата')</label>
                        <input wire:model.defer="employee.salary" type="number" step="1" min="0" class="form-control @error('employee.salary') is-invalid @enderror" id="employeeSalary">
                        <div class="invalid-feedback">
                            @error('employee.salary') <span class="error">{{ $message }}</span> @enderror
                        </div>
                    </div>
                    <div class="form-group mb-3">
                        <label for="employeeDepartments" class="form-label">@lang('Отделы')</label>
                        <select wire:model.defer="employee.departments" required multiple class="form-control select2 @error('employee.departments') is-invalid @enderror" id="employeeDepartments">
                            @foreach($departments as $department)
                                <option value="{{$department->id}}">{{$department->title}}</option>
                            @endforeach
                        </select>
                        <div class="invalid-feedback">
                            @error('employee.departments') <span class="error">{{ $message }}</span> @enderror
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">@lang('Отмена')</button>
                    <button type="submit" class="btn btn-primary" >@lang('Сохранить')</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/livewire/employees/index.blade.php
<div>
    @include('partials.alerts')

    <div class="card">
        <div class="card-header">
            @lang("Сотрудники")
        </div>
        <div class="card-body">
            <button wire:click="add()" type="button" class="btn btn-primary mb-3">@lang('Добавить')</button>
            <table class="table table-hover table-bordered">
                <thead>
                <tr>
                    <th scope="col">@lang('Имя')</th>
                    <th scope="col">@lang('Фамилия')</th>
                    <th scope="col">@lang('Отчество')</th>
                    <th scope="col">@lang('Пол')</th>
                    <th scope="col">@lang('Заработная плата')</th>
                    <th scope="col">@lang('Отделы')</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody>
                @foreach($employees as $employee)
                    <tr>
                        <td>{{$employee->first_name}}</td>
                        <td>{{$employee->last_name}}</td>
                        <td>{{$employee->middle_name}}</td>
                        <td>{{$employee->gender}}</td>
                        <td>{{$employee->salary}}</td>
                        <td>{{$employee->departments->implode('title', ', ')}}</td>
                        <td>
                            <button wire:click="edit({{$employee->id}})" type="button" class="btn btn-primary">@lang("Edit")</button>
                            <button wire:click="delete({{$employee->id}})" type="button" class="btn btn-danger">@lang("Delete")</button>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>

    @include('livewire.employees.add-modal')

    @section('scripts')
        <script>
            window.addEventListener('closeEmployeeModal',function (){
                $('#employeeModal').modal('hide');
            });
            window.addEventListener('showEmployeeModal',function (){
                $('#employeeModal').modal('show');
            });
        </script>
    @endsection
</div>

resources/views/livewire/grid.blade.php
<div>
    <div class="card">
        <div class="card-header">
            @lang("Сетка")
        </div>
        <div class="card-body">
            <table class="table table-hover table-bordered">
                <thead>
                <tr>
                    <th scope="col"></th>
                    @foreach($departments as $department)
                        <th scope="col" class="text-center">{{$department->title}}</th>
                    @endforeach
                </tr>
                </thead>
                <tbody>
                    @foreach($employees as $employee)
                        <tr>
                            <th scope="row">{{ $employee->first_name.' '.$employee->last_name }}</th>
                            @foreach($departments as $department)
                                <td class="text-center">@if($department->employees->contains($employee)) ✓ @endif</td>
                            @endforeach
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

resources/views/partials/alerts.blade.php
@if ($message = Session::get('success'))
    <div class="alert alert-success">
        <span>{!! $message !!}</span>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif

@if ($message = Session::get('warning'))
    <div class="alert alert-danger">
        <span>{!! $message !!}</span>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif

resources/views/partials/input-alerts.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>@lang('Упс!')</strong><p>@lang('Есть некоторые ошибки.')</p>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif